import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { CssBaseline, InitColorSchemeScript } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v16-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { PWAProvider } from 'next-pwa-pack';
import { theme } from '@/shared/model/theme';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang='ru' suppressHydrationWarning>
			<head>
				<InitColorSchemeScript attribute='class' />
			</head>
			<body>
				<PWAProvider>
					<AppRouterCacheProvider>
						<ThemeProvider theme={theme}>
							<CssBaseline enableColorScheme />

							<main>{children}</main>
						</ThemeProvider>
					</AppRouterCacheProvider>
				</PWAProvider>
			</body>
		</html>
	);
}
